name: Build and publish Docker image

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - .github/workflows/ci-build.yaml
      - .github/actions/build-push-wg-tunnel/**
      - cmd/**
      - internal/**
      - Dockerfile
      - go.*

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Publish OCI image
      attestations: write # Publish attestations
      id-token: write # Publish attestations

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          # We need the entire history to determine the current version
          fetch-depth: 0

      - name: Determine tag
        id: determine_tag
        env:
          TAG: ${{ (github.ref_type == 'tag' && github.ref_name) || 'latest' }}
        run: |
          echo "tag=${TAG#v}" >> "$GITHUB_OUTPUT"
          echo -n "revision=" >> "$GITHUB_OUTPUT"
          git describe >> "$GITHUB_OUTPUT"
          echo -n "date=" >> "$GITHUB_OUTPUT"
          date --iso-8601=seconds >> "$GITHUB_OUTPUT"

      - name: Build
        uses: ./.github/actions/build-push-wg-tunnel
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.determine_tag.outputs.tag }}
          revision: ${{ steps.determine_tag.outputs.revision }}
          date: ${{ steps.determine_tag.outputs.date }}
          push: true
